/-
Bases and subbases for a topology.

## Key definitions

- `IsBasis ℬ` : `ℬ` satisfies the requirements to be a basis
- `Topology.ofBasis ℬ` : the topology generated by `ℬ`

## Key theorems

-/
import MgwTopology.Section_12_Core

namespace Mgw

universe u
variable {α : Type u}

/-- `IsBasis ℬ` says `ℬ ⊆ Set α` is a topological basis on `α`:
    covers `α`, and the intersection of any two members is a union of members. -/
structure IsBasis (ℬ : Set (Set α)) : Prop where
  covers : ∀ x : α, ∃ B ∈ ℬ, x ∈ B
  inter  : ∀ B₁ ∈ ℬ, ∀ B₂ ∈ ℬ, ∀ x, x ∈ B₁ ∩ B₂ →
             ∃ B₃ ∈ ℬ, x ∈ B₃ ∧ B₃ ⊆ B₁ ∩ B₂

/-- Topology generated by a basis: open iff it is a union of basis members. -/
def Set.HasSubfamilyWhoseUnionIs (ℬ : Set (Set α)) : Set α → Prop :=
  fun U => ∀ x ∈ U, ∃ B ∈ ℬ, x ∈ B ∧ B ⊆ U

namespace Topology

/- source: topology.mg:7559 name: lemma_topology_from_basis -/
/-- The collection generated by a basis is indeed a topology. -/
def ofBasis (ℬ : Set (Set α)) (hℬ : IsBasis ℬ) : Topology α where
  IsOpen := ℬ.HasSubfamilyWhoseUnionIs
  isOpen_empty := by
    intro x hx; exact hx.elim
  isOpen_univ := by
    intro x _
    obtain ⟨B, hB, hxB⟩ := hℬ.covers x
    exact ⟨B, hB, hxB, fun _ _ => trivial⟩
  isOpen_inter := by
    intro U V hU hV x hxUV
    obtain ⟨B₁, hB₁, hxB₁, hB₁U⟩ := hU x hxUV.1
    obtain ⟨B₂, hB₂, hxB₂, hB₂V⟩ := hV x hxUV.2
    obtain ⟨B₃, hB₃, hxB₃, hB₃sub⟩ :=
      hℬ.inter B₁ hB₁ B₂ hB₂ x ⟨hxB₁, hxB₂⟩
    refine ⟨B₃, hB₃, hxB₃, ?_⟩
    intro y hy
    exact ⟨hB₁U (hB₃sub hy).1, hB₂V (hB₃sub hy).2⟩
  isOpen_sUnion := by
    intro 𝒰 h𝒰 x ⟨U, hU, hxU⟩
    obtain ⟨B, hB, hxB, hBU⟩ := h𝒰 U hU x hxU
    refine ⟨B, hB, hxB, ?_⟩
    intro y hy
    exact ⟨U, hU, hBU hy⟩

/-- Every basis element is open in the generated topology. -/
theorem basis_mem_isOpen {ℬ : Set (Set α)} (hℬ : IsBasis ℬ)
    {B : Set α} (hB : B ∈ ℬ) : (Topology.ofBasis ℬ hℬ).IsOpen B := by
  intro x hx
  exact ⟨B, hB, hx, fun _ h => h⟩

/- source: topology.mg:7877 name: open_sets_as_unions_of_basis -/
/-- In a topology generated by a basis `ℬ`, every open set is a union of
    basis elements. -/
theorem isOpen_iff_sUnion_of_basis {ℬ : Set (Set α)} (hℬ : IsBasis ℬ)
    (U : Set α) :
    (Topology.ofBasis ℬ hℬ).IsOpen U ↔
      ∃ 𝒰 : Set (Set α), (∀ V ∈ 𝒰, V ∈ ℬ) ∧ ⋃₀ 𝒰 = U := by
  refine ⟨?_, ?_⟩
  · intro hU
    refine ⟨fun V => V ∈ ℬ ∧ V ⊆ U, fun V h => h.1, ?_⟩
    ext x
    refine ⟨?_, ?_⟩
    · rintro ⟨V, ⟨_, hVU⟩, hxV⟩; exact hVU hxV
    · intro hxU
      obtain ⟨B, hB, hxB, hBU⟩ := hU x hxU
      exact ⟨B, ⟨hB, hBU⟩, hxB⟩
  · rintro ⟨𝒰, h𝒰, rfl⟩ x ⟨V, hV, hxV⟩
    exact ⟨V, h𝒰 V hV, hxV, fun y hy => ⟨V, hV, hy⟩⟩

/- source: topology.mg:7929 name: basis_generates_open_sets -/
/-- Conversely, any union of basis elements is open in the generated topology. -/
theorem isOpen_sUnion_of_basis {ℬ : Set (Set α)} (hℬ : IsBasis ℬ)
    {𝒰 : Set (Set α)} (h𝒰 : ∀ V ∈ 𝒰, V ∈ ℬ) :
    (Topology.ofBasis ℬ hℬ).IsOpen (⋃₀ 𝒰) :=
  (isOpen_iff_sUnion_of_basis hℬ _).2 ⟨𝒰, h𝒰, rfl⟩

/- source: topology.mg:8264 name: generated_topology_finer -/
/-- If `T` is a topology containing every basis element, then `T` is finer
    than the topology generated by `ℬ`: every `ofBasis`-open set is `T`-open. -/
theorem ofBasis_isOpen_of_containsBasis {ℬ : Set (Set α)}
    (hℬ : IsBasis ℬ) (T : Topology α) (hT : ∀ B ∈ ℬ, T.IsOpen B)
    {U : Set α} (hU : (Topology.ofBasis ℬ hℬ).IsOpen U) : T.IsOpen U := by
  -- U is a union of basis elements; each basis element is T-open.
  obtain ⟨𝒰, h𝒰, rfl⟩ := (isOpen_iff_sUnion_of_basis hℬ U).1 hU
  exact T.isOpen_sUnion (fun V hV => hT V (h𝒰 V hV))

/- source: topology.mg:8173 name: finer_via_basis -/
/-- Lemma 13.3 (Munkres): if at every point of every basis element of `ℬ`
    there is a basis element of `ℬ'` fitting inside it, then the topology
    generated by `ℬ'` is finer than the one generated by `ℬ`. -/
theorem ofBasis_finer_of_refines
    {ℬ ℬ' : Set (Set α)} (hℬ : IsBasis ℬ) (hℬ' : IsBasis ℬ')
    (hrefine : ∀ x : α, ∀ B ∈ ℬ, x ∈ B →
                 ∃ B' ∈ ℬ', x ∈ B' ∧ B' ⊆ B)
    {U : Set α} (hU : (Topology.ofBasis ℬ hℬ).IsOpen U) :
    (Topology.ofBasis ℬ' hℬ').IsOpen U := by
  intro x hxU
  obtain ⟨B, hB, hxB, hBU⟩ := hU x hxU
  obtain ⟨B', hB', hxB', hB'B⟩ := hrefine x B hB hxB
  exact ⟨B', hB', hxB', Set.Subset.trans hB'B hBU⟩

/-! ### §13 Subbases: topology generated by an arbitrary family. -/

/-- Basis obtained from an arbitrary family `S` by taking finite intersections
    of members of `S` (including the empty intersection = `Set.univ`). -/
def basisFromSubbasis (S : Set (Set α)) : Set (Set α) :=
  fun B => ∃ (n : Nat) (f : Fin n → Set α),
    (∀ i, f i ∈ S) ∧ B = (fun x => ∀ i : Fin n, x ∈ f i)

/-- Every member of `S` is a member of the finite-intersection basis. -/
theorem mem_basisFromSubbasis_of_mem {S : Set (Set α)} {U : Set α}
    (hU : U ∈ S) : U ∈ basisFromSubbasis S := by
  refine ⟨1, fun _ => U, fun _ => hU, ?_⟩
  ext x
  refine ⟨fun hx _ => hx, fun h => h 0⟩

/-- The whole space is a member of the finite-intersection basis (empty
    intersection). -/
theorem univ_mem_basisFromSubbasis (S : Set (Set α)) :
    (Set.univ : Set α) ∈ basisFromSubbasis S := by
  refine ⟨0, Fin.elim0, fun i => i.elim0, ?_⟩
  ext x
  exact ⟨fun _ i => i.elim0, fun _ => trivial⟩

/-- The finite-intersection family is actually a basis. -/
theorem isBasis_basisFromSubbasis (S : Set (Set α)) :
    IsBasis (basisFromSubbasis S) where
  covers := by
    intro x
    exact ⟨Set.univ, univ_mem_basisFromSubbasis S, trivial⟩
  inter := by
    rintro B₁ ⟨n₁, f₁, hf₁, rfl⟩ B₂ ⟨n₂, f₂, hf₂, rfl⟩ x hx
    -- Concatenate the indices.
    let g : Fin (n₁ + n₂) → Set α := fun i =>
      if h : i.val < n₁ then f₁ ⟨i.val, h⟩
      else f₂ ⟨i.val - n₁, by have := i.isLt; omega⟩
    have hg_mem : ∀ i, g i ∈ S := by
      intro i
      show (if h : i.val < n₁ then f₁ ⟨i.val, h⟩
            else f₂ ⟨i.val - n₁, by have := i.isLt; omega⟩) ∈ S
      split
      · exact hf₁ _
      · exact hf₂ _
    let B₃ : Set α := fun y => ∀ i : Fin (n₁ + n₂), y ∈ g i
    have hB₃_mem : B₃ ∈ basisFromSubbasis S := ⟨n₁ + n₂, g, hg_mem, rfl⟩
    have hxB₃ : B₃ x := by
      intro i
      show x ∈ (if h : i.val < n₁ then f₁ ⟨i.val, h⟩
                else f₂ ⟨i.val - n₁, by have := i.isLt; omega⟩)
      split
      · next h =>
        have := hx.1 ⟨i.val, h⟩
        exact this
      · next h =>
        have := hx.2 ⟨i.val - n₁, by have := i.isLt; omega⟩
        exact this
    refine ⟨B₃, hB₃_mem, hxB₃, ?_⟩
    intro y hy
    refine ⟨fun i => ?_, fun i => ?_⟩
    · have hlt : i.val < n₁ + n₂ := by have := i.isLt; omega
      have := hy ⟨i.val, hlt⟩
      show y ∈ f₁ i
      have hg_eq : g ⟨i.val, hlt⟩ = f₁ i := by
        show (if h : i.val < n₁ then f₁ ⟨i.val, h⟩
              else f₂ ⟨i.val - n₁, by have := i.isLt; omega⟩) = f₁ i
        rw [dif_pos i.isLt]
      rw [hg_eq] at this; exact this
    · have hlt : n₁ + i.val < n₁ + n₂ := by have := i.isLt; omega
      have := hy ⟨n₁ + i.val, hlt⟩
      show y ∈ f₂ i
      have hg_eq : g ⟨n₁ + i.val, hlt⟩ = f₂ i := by
        show (if h : n₁ + i.val < n₁ then f₁ ⟨n₁ + i.val, h⟩
              else f₂ ⟨n₁ + i.val - n₁, by have := i.isLt; omega⟩) = f₂ i
        have h1 : ¬ (n₁ + i.val) < n₁ := by have := i.isLt; omega
        rw [dif_neg h1]
        have hfeq : (⟨n₁ + i.val - n₁, by have := i.isLt; omega⟩ : Fin n₂) = i := by
          apply Fin.ext; show n₁ + i.val - n₁ = i.val; omega
        rw [hfeq]
      rw [hg_eq] at this; exact this

/-- The topology generated by a subbasis `S`: the topology of the basis of
    finite intersections of elements of `S`. No preconditions on `S`. -/
def ofSubbasis (S : Set (Set α)) : Topology α :=
  Topology.ofBasis (basisFromSubbasis S) (isBasis_basisFromSubbasis S)

/-- Every element of the subbasis `S` is open in `Topology.ofSubbasis S`. -/
theorem ofSubbasis_isOpen_of_mem {S : Set (Set α)} {U : Set α}
    (hU : U ∈ S) : (Topology.ofSubbasis S).IsOpen U :=
  basis_mem_isOpen (isBasis_basisFromSubbasis S) (mem_basisFromSubbasis_of_mem hU)

/-- A finite intersection of subbasis elements is open in the generated
    topology. -/
theorem ofSubbasis_isOpen_finInter {S : Set (Set α)}
    {n : Nat} {f : Fin n → Set α} (hf : ∀ i, f i ∈ S) :
    (Topology.ofSubbasis S).IsOpen (fun x => ∀ i : Fin n, x ∈ f i) :=
  basis_mem_isOpen (isBasis_basisFromSubbasis S) ⟨n, f, hf, rfl⟩

/-- If a topology `T` contains every element of `S`, then `T` is finer than the
    topology generated by `S` as a subbasis. -/
theorem ofSubbasis_isOpen_of_containsSubbasis
    {S : Set (Set α)} (T : Topology α) (hT : ∀ U ∈ S, T.IsOpen U)
    {V : Set α} (hV : (Topology.ofSubbasis S).IsOpen V) : T.IsOpen V := by
  apply ofBasis_isOpen_of_containsBasis (isBasis_basisFromSubbasis S) T ?_ hV
  rintro B ⟨n, f, hf, rfl⟩
  -- Finite intersection of opens is open.
  exact T.isOpen_iInter_fin_of_subbasis hT f hf

end Topology

end Mgw
