/-
The order topology.

Corresponds to topology.mg §14 (Order Topology), real-free parts only.
We parametrise over a strict order `<` on `α` (given as a binary relation),
following Munkres' "simply ordered set" (= strict linear order).
-/
import MgwTopology.Basis

namespace Mgw
namespace Topology

universe u
variable {α : Type u}

/-- An open ray above `a`: `{x | a < x}`. -/
def openRayAbove (lt : α → α → Prop) (a : α) : Set α :=
  fun x => lt a x

/-- An open ray below `b`: `{x | x < b}`. -/
def openRayBelow (lt : α → α → Prop) (b : α) : Set α :=
  fun x => lt x b

/-- Open interval `(a, b) = {x | a < x ∧ x < b}`. -/
def openInterval (lt : α → α → Prop) (a b : α) : Set α :=
  fun x => lt a x ∧ lt x b

/-- The standard-order basis: all open intervals, plus `openRayAbove a` when
    `a` is a "minimum-like" element (there is no `y < a`), and
    `openRayBelow b` when `b` is "maximum-like". For a Munkres-style
    simply-ordered set this is a basis. We bundle all three families. -/
def orderBasis (lt : α → α → Prop) : Set (Set α) :=
  fun B =>
    (∃ a b, B = openInterval lt a b) ∨
    (∃ a, (∀ y, ¬ lt y a) ∧ B = openRayAbove lt a) ∨
    (∃ b, (∀ y, ¬ lt b y) ∧ B = openRayBelow lt b)

/-! ### Elementary lemmas about open rays / intervals. -/

theorem openInterval_subset_openRayAbove
    (lt : α → α → Prop) (a b : α) :
    openInterval lt a b ⊆ openRayAbove lt a :=
  fun _ h => h.1

theorem openInterval_subset_openRayBelow
    (lt : α → α → Prop) (a b : α) :
    openInterval lt a b ⊆ openRayBelow lt b :=
  fun _ h => h.2

theorem openRayAbove_inter_openRayBelow
    (lt : α → α → Prop) (a b : α) :
    openRayAbove lt a ∩ openRayBelow lt b = openInterval lt a b := by
  ext x; exact Iff.rfl

/-- A strict linear order: irreflexive, transitive, and connex (trichotomous
    apart from equality). -/
structure StrictLinearOrder (lt : α → α → Prop) : Prop where
  irrefl : ∀ a, ¬ lt a a
  trans  : ∀ {a b c}, lt a b → lt b c → lt a c
  trichot : ∀ a b, lt a b ∨ a = b ∨ lt b a

namespace StrictLinearOrder

theorem asymm {lt : α → α → Prop} (h : StrictLinearOrder lt)
    {a b : α} (hab : lt a b) : ¬ lt b a := by
  intro hba; exact h.irrefl a (h.trans hab hba)

theorem ne_of_lt {lt : α → α → Prop} (h : StrictLinearOrder lt)
    {a b : α} (hab : lt a b) : a ≠ b := by
  intro e; rw [e] at hab; exact h.irrefl b hab

end StrictLinearOrder

/-! ### The order topology (direct definition via a generating family). -/

/- source: topology.mg:27980 name: order_topology_is_topology -/
/-- The order topology as the topology generated by `orderBasis lt` (as a
    *family of open sets*, i.e. a set is open iff it is a union of basis
    elements). We package it as a `Topology` here under the assumption that
    the given family is a basis (provable for strict linear orders, but we
    state the general version parametrically). -/
def order (lt : α → α → Prop) (hb : IsBasis (orderBasis lt)) : Topology α :=
  Topology.ofBasis (orderBasis lt) hb

/-- Convenience: open rays above a minimum are open in the order topology. -/
theorem order_openRayAbove_isOpen
    (lt : α → α → Prop) (hb : IsBasis (orderBasis lt))
    (a : α) (hmin : ∀ y, ¬ lt y a) :
    (order lt hb).IsOpen (openRayAbove lt a) :=
  Topology.basis_mem_isOpen hb (Or.inr (Or.inl ⟨a, hmin, rfl⟩))

/-- Convenience: open rays below a maximum are open in the order topology. -/
theorem order_openRayBelow_isOpen
    (lt : α → α → Prop) (hb : IsBasis (orderBasis lt))
    (b : α) (hmax : ∀ y, ¬ lt b y) :
    (order lt hb).IsOpen (openRayBelow lt b) :=
  Topology.basis_mem_isOpen hb (Or.inr (Or.inr ⟨b, hmax, rfl⟩))

/-- Convenience: every open interval is open in the order topology. -/
theorem order_openInterval_isOpen
    (lt : α → α → Prop) (hb : IsBasis (orderBasis lt))
    (a b : α) :
    (order lt hb).IsOpen (openInterval lt a b) :=
  Topology.basis_mem_isOpen hb (Or.inl ⟨a, b, rfl⟩)

end Topology
end Mgw
