/-
Indexed product topology (finite index / box topology version).

Corresponds to topology.mg §19 (Product Topology, finite parts).

Since a "finite" product is the same as the box product for an arbitrary
index type when only finitely many coordinates are constrained, we formalise
both the box topology and the (standard) product topology generated by the
subbasis of single-coordinate open cylinders.

Only a small amount of §19 is ported here — enough to define the product
topology, state the characterising universal property, and prove
projection continuity. Deeper results (e.g. product-of-Hausdorff) are
deferred to a later phase.
-/
import MgwTopology.Basis
import MgwTopology.Continuous

namespace Mgw
namespace Topology

universe u v w
variable {ι : Type u} {X : ι → Type v} {γ : Type w}

/-- Single-coordinate open cylinder: `{f | f i ∈ U}`. -/
def cylinder (i : ι) (U : Set (X i)) : Set (∀ j, X j) :=
  fun f => f i ∈ U

/-- Preimage of an open set under the `i`-th projection equals the cylinder. -/
theorem proj_preimage_eq_cylinder (i : ι) (U : Set (X i)) :
    ((fun f : ∀ j, X j => f i) ⁻¹' U) = cylinder i U := rfl

/-- Box-topology basis: products `∀ i, f i ∈ B i` with each `B i` open. -/
def boxBasis (T : ∀ i, Topology (X i)) : Set (Set (∀ j, X j)) :=
  fun W => ∃ B : ∀ i, Set (X i), (∀ i, (T i).IsOpen (B i)) ∧ W = fun f => ∀ i, f i ∈ B i

/-- The box basis is a basis. -/
theorem isBasis_boxBasis (T : ∀ i, Topology (X i)) :
    IsBasis (boxBasis T) where
  covers := by
    intro f
    refine ⟨(fun g : ∀ j, X j => ∀ i, g i ∈ (Set.univ : Set (X i))),
      ⟨fun i => Set.univ, fun _ => (T _).isOpen_univ, rfl⟩, ?_⟩
    intro _; trivial
  inter := by
    rintro B₁ ⟨b₁, hb₁, rfl⟩ B₂ ⟨b₂, hb₂, rfl⟩ f hf
    refine ⟨(fun g => ∀ i, g i ∈ b₁ i ∩ b₂ i),
      ⟨fun i => b₁ i ∩ b₂ i, fun i => (T i).isOpen_inter (hb₁ i) (hb₂ i), rfl⟩,
      ?_, ?_⟩
    · intro i; exact ⟨hf.1 i, hf.2 i⟩
    · intro g hg
      exact ⟨fun i => (hg i).1, fun i => (hg i).2⟩

/-- The box product topology: generated by the box basis.
    For finite `ι` this coincides with Munkres' product topology; for infinite
    `ι` this is strictly finer than the product topology. -/
def boxProduct (T : ∀ i, Topology (X i)) : Topology (∀ i, X i) :=
  Topology.ofBasis (boxBasis T) (isBasis_boxBasis T)

/-- Every projection from the box product is continuous. -/
theorem boxProduct_proj_continuous
    (T : ∀ i, Topology (X i)) (i : ι) :
    Continuous (boxProduct T) (T i) (fun f : ∀ j, X j => f i) := by
  intro U hU
  -- preimage = { f | f i ∈ U }.  Open-rectangle: set b j = univ for j ≠ i and b i = U.
  classical
  apply (boxProduct T).isOpen_of_local_nhd
  intro f hf
  -- f i ∈ U, so use rectangle.
  refine ⟨fun g => ∀ j, g j ∈ (if h : j = i then h ▸ U else Set.univ),
    ?_, ?_, ?_⟩
  · -- box basis member → open.
    refine basis_mem_isOpen (isBasis_boxBasis T)
      ⟨fun j => if h : j = i then h ▸ U else Set.univ, ?_, rfl⟩
    intro j
    by_cases h : j = i
    · subst h; simp only [dite_true]; exact hU
    · simp only [h, dite_false]; exact (T j).isOpen_univ
  · intro j
    by_cases h : j = i
    · subst h; simp only [dite_true]; exact hf
    · simp only [h, dite_false]; trivial
  · intro g hg
    have : g i ∈ U := by
      have := hg i
      simp only [dite_true] at this
      exact this
    exact this

/-- Rectangle opens are open in the box product. -/
theorem boxProduct_isOpen_rect
    (T : ∀ i, Topology (X i)) {B : ∀ i, Set (X i)}
    (hB : ∀ i, (T i).IsOpen (B i)) :
    (boxProduct T).IsOpen (fun f => ∀ i, f i ∈ B i) :=
  basis_mem_isOpen (isBasis_boxBasis T) ⟨B, hB, rfl⟩

/-- Projection out of the box product, as a convenience corollary. -/
theorem boxProduct_proj_component
    (T : ∀ i, Topology (X i)) (i : ι)
    {U : Set (X i)} (hU : (T i).IsOpen U) :
    (boxProduct T).IsOpen (cylinder i U) := by
  rw [← proj_preimage_eq_cylinder]
  exact boxProduct_proj_continuous T i U hU

end Topology
end Mgw
